name = "LiebLinigerBetheAnsatz"
uuid = "edc2cedd-d8c0-480a-8582-a07a8a1a7c38"
authors = ["Akshay Shankar"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DrWatson = "2.19.1"
LaTeXStrings = "1.4.0"
Reexport = "1.2.2"
Test = "1.11.0"
julia = "1.11.7"
